# Generated by Django 2.0.5 on 2018-05-18 17:46

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='quote',
            managers=[
                ('quotes', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='quote',
            name='text',
            field=models.CharField(max_length=256),
        ),
    ]
